### ISSUE TITLE
Using WalletConnect Provider

### ISSUE THREAD

**Issue by aaronmgdr** [VGLoic/eth-testing#43]
First off Big Thank you for this project. 

For metamask the examples guided me well in setting up my tests. 

Im having some trouble understand how to use it to test connections for WalletConnect connections.  

```
describe('WalletConnectConnector', () => {
  const testingUtils = generateTestingUtils({
    providerType: 'WalletConnect',
  });
  beforeAll(() => {
    testingUtils.getProvider(); // should I be setting something equal to this?
    
    testingUtils.mockNotConnectedWallet();
    testingUtils.mockAccounts([ACCOUNT]);
  });
    // tests here
]);    
```

**Comment by VGLoic** [comment]
Hey @aaronmgdr ! Thanks a lot for the issue and the kind words :)

So here is an [example](https://github.com/VGLoic/eth-testing/tree/main/examples/react-apps/src/pages/wallet-connect-connection) with WalletConnect, please tell me if it helps you :).

It's not super elegant unfortunately, it's using directly the `WalletConnectProvider` from `@walletconnect/web3-provider` and not any wrapper library such as `web3-react` or `wagmi` 😅 

If you're using some wrapper library and can't properly mock, tell me, I need to do examples with these libraries at some point anyway so I will be happy to dig in :)

**Comment by aaronmgdr** [comment]
Im using it to write tests for https://github.com/celo-org/use-contractkit Worked well for metamask but for WalletConnect we are using our own implementation so there is no `@walletconnect/web3-provider` instead there is a Wallet and a Signer. 

Was hoping against hope there would still be away to use together but looks unlikely.

**Comment by VGLoic** [comment]
From what I see, the `import WalletConnect from '@walletconnect/client-v1'` is used under the hood and I did not find the `web3 provider` part of it, i.e. the conventional object used in order to interact via Json RPC to the remote node. Since this is the part that needs to be replaced/mocked, I am not sure that the current state of this library can help you on that unfortunately :(
