### ISSUE TITLE
How do i use this package when i use web3react package?

### ISSUE THREAD

**Issue by Zorig** [VGLoic/eth-testing#47]
### Open

So i am using `web3react` package and its provider(`getLibrary`). How can i use this the package with this situation? 

My components are using `useweb3react` hook and its properties heavily

**Comment by Zorig** [comment]
Thank you for detailed comment. I'm using web3-react V6 right now. 

My whole app is wrapped by `Web3ReactProvider getLibrary={getLibrary}>` does this still same as `<Web3Provider connectors={...} getLibrary={...} >{children}</Web3Provider>`. I thought if i set the testingUtils and wallet address, then when i check the `const { active, account} = useWeb3React()` should return the wallet address which i set in testingUtils right? Unfortunately its returning `undefined` for my case.

**Comment by VGLoic** [comment]
Hey @Zorig 

I dig a bit and there was indeed a missing piece on the side of this package!

I fixed it for MetaMask for now and added an example of test for connection using `web3-react` and `MetaMask` :)

I will probably merge this during the day but don't hesitate to take a look at #48 :)

I will need to check for other wallets later on!

**Comment by Zorig** [comment]
@VGLoic thanks for such a rapid fix. In my case, just a Metamask is enough for now. It seems, currently working as expected in the previous comment right? Sorry for bringing up another problem again. Is it possible to mock the signature request?  I saw the example test and tried `lowLevel` API and nothing happened, is it because of the missing piece that you mentioned?

**Comment by VGLoic** [comment]
@Zorig 
You can find examples with signing message, the tests are called `User should be able to sign a transaction` in the examples folder :)

Basically you have two possibilities

1. If the message is known in advance, you can do something like
```ts
    const randomWallet = ethers.Wallet.createRandom();
    const message = 'My message';
    const signature = await randomWallet.signMessage(message);
    testingUtils.lowLevel.mockRequest("personal_sign", signature);

    ... rest of the test
```
2. Is the message is dynamic/not known beforehand, then you can use another form (the one in the example actually):
```ts
    const randomWallet = ethers.Wallet.createRandom();
    testingUtils.lowLevel.mockRequest("personal_sign", async (params: [string]) => {
      const message = params[0];
      const signature = await randomWallet.signMessage(message);
      return signature;
    });
   ...rest of the test
```

Don't hesitate to try with that, if there is an additional issue, I will be happy to dig into that :)

I'm gonna merge the PR in order that you have the new version available

**Comment by Zorig** [comment]
Thank you so much.

**Comment by VGLoic** [comment]
@Zorig I finally added the signature to the test example 😂 it should work as expected, keep me posted if it is not working!
