### ISSUE TITLE
Add Coinbase Wallet provider

### ISSUE THREAD

**Issue by plondon** [VGLoic/eth-testing#58]
### What is the new or updated feature that you are suggesting?

First of all, thanks so much for the great library!

Create a new provider type that works similarly to the metamask provider, but has the `isCoinbaseWallet` field instead of `isMetaMask`.

### Why should this feature be included?

I'd like to be able to test both metamask and coinbase wallet extensions/providers.

**Comment by VGLoic** [comment]
Hey @plondon! Thanks a lot for the issue and the kind word! 

I'll try to handle this tomorrow :)

**Comment by plondon** [comment]
You rock, thanks!
