### ISSUE TITLE
Enable dynamic response and timing for mockCall 

### ISSUE THREAD

**Issue by lukemelia** [VGLoic/eth-testing#61]
### What is the new or updated feature that you are suggesting?

I am working on a feature where I need to make assertions on the in-progress phase of a smart contract function invocation. I would like to be able to provide a Promise-returning callback to `mockCall` as an alternative to passing the return values. The callback would be invoked at the time of the call and be passed the parameters the mocked function was invoked with. The resolved value of the promise would become the return value of the function invocation.

For example:

```js
    const mockContract = mockWalletConnect.generateContractUtils(ContractABI, CONTRACT_ADDRESS);
    const myFunctionDelay = new Deferred();
    mockContract.mockCall('someFunction', async (params) => {
      await myFunctionDelay.promise;
      return ["Example return value"]
    });

    // Later, cause the system under test to make the contract call
    // Then assert the in-progress state is correct
    // Finally, trigger the smart contract function to complete
    myFunctionDelay.resolve();
```

  

### Why should this feature be included?

It allows detailed control over the timing of asynchronous JSON RPC calls so that you can easily test the state of your system during the transient (but very real) period where you are waiting for the provider to return.

**Comment by VGLoic** [comment]
Hey @lukemelia ! Thanks a lot for this issue :)

I have created the PR #62 in order to solve this issue, don't hesitate to take a look! Without news, I will merge this in ~12h :)
