### ISSUE TITLE
incompatible with node 16

### ISSUE THREAD

**Issue by code3z** [VGLoic/eth-testing#9]
Error upon install: 
```bash
error eth-testing@1.0.2-alpha: The engine "node" is incompatible with this module. Expected version "^12 || ^14 || ^15". Got "16.13.2"
```

**Comment by VGLoic** [comment]
Hey @code3z! Thanks a lot for the issue!

I messed up a few things at the origin publication of this project, now I moved everything under the `alpha` distribution so if we use `npm install --save-dev eth-testing@alpha` everything should be fine :)

I updated the README in this [PR](https://github.com/VGLoic/eth-testing/pull/11) if you wanna take a look :)

**Comment by code3z** [comment]
Great!
